### ISSUE TITLE
CarGenerator.json containing Many Duplicates

### ISSUE THREAD

**Issue by WhishN** [KWMSources/ParkedVehicleSpawner#3]
see title :D

there are a lot of duplicate lines.

one for example: 
{ "Position": { "X": 222.4588, "Y": -804.3337, "Z": 32.64424 }, "OrientX": -5.621367, "OrientY": 2.097671, "PerpendicularLength": 300000000.0, "CarModel": "", "Flags": 3616, "PopGroup": "" },
Exists 5 Times!

**Comment by WhishN** [comment]
This Should have removed all duplicates (used a vscode tool for it)

[spots.zip](https://github.com/KWMSources/ParkedVehicleSpawner/files/4902842/spots.zip)

**Comment by KWMSources** [comment]
Solved with the commit, thanks for the new json!
